### ISSUE TITLE
where is the json data

### ISSUE THREAD

**Issue by flyonok** [neouyghur/One-stage-Mask-based-Scene-Text-Eraser#1]
Hi, @neouyghur 
Where is the content of '/media/osman/megamind/SynthText/OxfordSynthText/test.json' and other json data, can you put it here, thanks.

**Comment by neouyghur** [comment]
those contents are added.

**Comment by neouyghur** [comment]
@flyonok  the dataset size is too big to upload. I upload the script for generating these jason files. It is under the scrips folder.

**Comment by flyonok** [comment]
OK，thanks.
