### ISSUE TITLE
What is the ‘GT.mat’ file in making jason files?

### ISSUE THREAD

**Issue by sapphireh** [neouyghur/One-stage-Mask-based-Scene-Text-Eraser#5]
What is the GT.mat needed in script ‘create_Oxford_dataset.py’ ？
How can i make it for SCUT dataset?

**Comment by neouyghur** [comment]
@sapphireh GT.mat is provided by the oxford synthetic dataset. you can download from this link: https://www.robots.ox.ac.uk/~vgg/data/scenetext/. For SCUT you don't need to GT.mat. I already provided the json files for the SCUT dataset, so you don't need to generate json files for training and testing.

**Comment by sapphireh** [comment]
Thank you for your reply, I will try it now. I still have a question about the SCUT dataset. The author of SCUT dataset has released a new real world scene text removal dataset, called "SCUT-Enstext". So, could you provide the json files for that new datasets or just upload the script and I can  make json files for it by myself?

**Comment by neouyghur** [comment]
@sapphireh You are welcome. I have uploaded related scripts to the `scripts` folder. I don't guarantee it will work without editing, but you will get the idea if you carefully read the code. I remember SCUT does not provide `bbox` info, so I also upload a script for generating bbox.
