### ISSUE TITLE
How can i train the MTRNet++ on the scut-enstext  dataset?

### ISSUE THREAD

**Issue by GuangtaoLyu** [neouyghur/One-stage-Mask-based-Scene-Text-Eraser#8]
Can you provide a sample script for training?  I want to train the network on the scut-enstext and my datasets.

**Comment by neouyghur** [comment]
For training, you can just run `python main.py --config config/config_SCUT.yml`. For more details, check the parameters of the related config file.

**Comment by GuangtaoLyu** [comment]
> For training, you can just run `python main.py --config config/config_SCUT.yml`. For more details, check the parameters of the related config file.

thank you
